"""empty message

Revision ID: 3a4b3228a9da
Revises: b904f194913c
Create Date: 2023-07-10 20:32:56.362009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a4b3228a9da'
down_revision = 'b904f194913c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_helpdesk_permission', sa.Boolean(), nullable=False, server_default=str(False)))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_helpdesk_permission')
    # ### end Alembic commands ###
