"""empty message

Revision ID: b904f194913c
Revises: 27ab3db07de3
Create Date: 2023-07-08 19:46:43.101106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b904f194913c'
down_revision = '27ab3db07de3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(length=50), nullable=True))
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
